// Deterministic metadata fallback hierarchy for social + SEO tags.
//
//   1. page-specific content (an article's / project's own localized title, description, image)
//   2. localized public SiteSettings
//   3. committed Web defaults (the i18n `seo.*` strings and the committed social asset)
//
// WHY THE COMMITTED TIER IS A *FLOOR*, NOT A LAST RESORT REACHED BY ERROR HANDLING: the
// site-wide owner (`app.vue`) emits tier 3 unconditionally, with no API read at all, and pages
// override it with tiers 1/2 when they have real values. So "a temporary Settings API failure
// must not remove the title, description or image" is true BY CONSTRUCTION — there is no
// failure path that can empty a tag, because the tag was never sourced from the API in the
// first place. Nothing here depends on hydration, `window`, storage or a post-mount request.
//
// Blank handling is the subtle half: `null`/`undefined`/`''` are the obvious cases, but a
// whitespace-only CMS value ("   ") is the one that slips through and renders an empty-looking
// tag. `isBlank` treats all four as missing.

/** `null`, `undefined`, empty and whitespace-only all count as missing. */
export function isBlank(value: unknown): boolean {
  return typeof value !== 'string' || value.trim().length === 0
}

/**
 * First non-blank candidate, trimmed. Returns `undefined` when every tier is blank, so callers
 * can omit the tag entirely rather than emitting an empty one.
 */
export function pickMeta(...candidates: readonly unknown[]): string | undefined {
  for (const candidate of candidates) {
    if (!isBlank(candidate)) return (candidate as string).trim()
  }
  return undefined
}

// The committed branded social preview. Generated by the Docs repo's `brand:social` from the
// governed mark, fonts and palette, then committed here — the Web has no build-time, runtime or
// deployment dependency on Docs, and this file is served from `public/` so it stays available
// when the Settings API and the media API are both down.
//
// NOT the favicon: the favicon is a 1:1 icon and is explicitly disqualified as a social preview.
export const SOCIAL_IMAGE_PATH = '/social-card.png'
export const SOCIAL_IMAGE_WIDTH = 1200
export const SOCIAL_IMAGE_HEIGHT = 630

/**
 * Absolute URL for a social image. Open Graph and Twitter both require absolute URLs — a
 * relative one is silently dropped by most crawlers — so a blank or relative `siteUrl` must
 * yield `undefined` (omit the tag) rather than a broken relative value.
 *
 * `path` may already be absolute (a media-API URL), in which case it is returned unchanged.
 */
// Formats that social platforms render reliably. WebP and AVIF are deliberately absent: WhatsApp
// in particular handles them inconsistently, and a preview that silently fails is worse than a
// generic-but-working one.
const SHAREABLE_IMAGE_FORMATS = /^(png|jpe?g)$/i

/**
 * Is this entity image positively known to be a format social platforms render reliably?
 *
 * "Positively known" is the bar, not "not known to be bad": WebP, AVIF, an unknown format, and a
 * URL with no extension all return false, so the caller falls back to the committed PNG. A
 * declared MIME/format field wins over the URL when one is present; the URL extension is
 * consulted only because the current `PublicMediaImageDescriptor` has no such field — it carries
 * `kind: IMAGE | PDF`, which does not distinguish PNG from WebP.
 *
 * NOTE ON TODAY'S CONTRACT: `descriptor.url` is documented as the "widest PUBLIC WebP rendition",
 * so in practice this returns false for every entity image the API currently serves and the
 * committed PNG is always used. The gate exists so that a real PNG/JPEG social rendition — the
 * recorded media-pipeline follow-up — starts being honoured with no further change here.
 */
function isShareableImageFormat(
  descriptor: { url?: string | null, mimeType?: string | null, format?: string | null } | null | undefined,
): boolean {
  const declared = pickMeta(descriptor?.mimeType, descriptor?.format)
  if (declared) {
    return SHAREABLE_IMAGE_FORMATS.test(declared.replace(/^image\//i, ''))
  }

  const url = pickMeta(descriptor?.url)
  if (!url) return false

  // Compare the extension only, never the query string — `?w=1` must not read as a format.
  const extension = url.split(/[?#]/)[0]?.match(/\.([a-z0-9]+)$/i)?.[1]
  return Boolean(extension && SHAREABLE_IMAGE_FORMATS.test(extension))
}

/**
 * Social-image tags for an entity (article / project) that may carry its own `ogImage`.
 *
 * Returns ALL of the image tags together, or `undefined` when the entity has no usable image.
 * Returning them as a set is the point: `og:image:width`/`height`/`alt` describe a specific
 * file, so overriding the image while inheriting the committed 1200×630 dimensions from the
 * site-wide owner would emit tags that contradict each other. A caller that gets `undefined`
 * simply emits nothing and inherits the complete committed set.
 */
export function entitySocialImage(
  descriptor: { url?: string | null, width?: number | null, height?: number | null, alt?: string | null, mimeType?: string | null, format?: string | null } | null | undefined,
  siteUrl: unknown,
): { url: string, width: number | undefined, height: number | undefined, alt: string | undefined } | undefined {
  if (!isShareableImageFormat(descriptor)) return undefined

  const url = absoluteSocialUrl(descriptor?.url, siteUrl)
  if (!url) return undefined

  return {
    url,
    width: descriptor?.width ?? undefined,
    height: descriptor?.height ?? undefined,
    alt: pickMeta(descriptor?.alt),
  }
}

export function absoluteSocialUrl(path: unknown, siteUrl: unknown): string | undefined {
  const candidate = pickMeta(path)
  if (!candidate) return undefined
  if (/^https?:\/\//i.test(candidate)) return candidate

  const base = pickMeta(siteUrl)
  if (!base || !/^https?:\/\//i.test(base)) return undefined

  return `${base.replace(/\/+$/, '')}/${candidate.replace(/^\/+/, '')}`
}
