// Deterministic metadata fallback hierarchy for social + SEO tags.
//
//   1. page-specific content (an article's / project's own localized title, description, image)
//   2. localized public SiteSettings
//   3. committed Web defaults (the i18n `seo.*` strings and the committed social asset)
//
// WHY THE COMMITTED TIER IS A *FLOOR*, NOT A LAST RESORT REACHED BY ERROR HANDLING: the
// site-wide owner (`app.vue`) emits tier 3 unconditionally, with no API read at all, and pages
// override it with tiers 1/2 when they have real values. So "a temporary Settings API failure
// must not remove the title, description or image" is true BY CONSTRUCTION — there is no
// failure path that can empty a tag, because the tag was never sourced from the API in the
// first place. Nothing here depends on hydration, `window`, storage or a post-mount request.
//
// Blank handling is the subtle half: `null`/`undefined`/`''` are the obvious cases, but a
// whitespace-only CMS value ("   ") is the one that slips through and renders an empty-looking
// tag. `isBlank` treats all four as missing.

/** `null`, `undefined`, empty and whitespace-only all count as missing. */
export function isBlank(value: unknown): boolean {
  return typeof value !== 'string' || value.trim().length === 0
}

/**
 * First non-blank candidate, trimmed. Returns `undefined` when every tier is blank, so callers
 * can omit the tag entirely rather than emitting an empty one.
 */
export function pickMeta(...candidates: readonly unknown[]): string | undefined {
  for (const candidate of candidates) {
    if (!isBlank(candidate)) return (candidate as string).trim()
  }
  return undefined
}

// The committed branded social preview. Generated by the Docs repo's `brand:social` from the
// governed mark, fonts and palette, then committed here — the Web has no build-time, runtime or
// deployment dependency on Docs, and this file is served from `public/` so it stays available
// when the Settings API and the media API are both down.
//
// NOT the favicon: the favicon is a 1:1 icon and is explicitly disqualified as a social preview.
export const SOCIAL_IMAGE_PATH = '/social-card.png'
export const SOCIAL_IMAGE_WIDTH = 1200
export const SOCIAL_IMAGE_HEIGHT = 630

/**
 * Absolute URL for a social image. Open Graph and Twitter both require absolute URLs — a
 * relative one is silently dropped by most crawlers — so a blank or relative `siteUrl` must
 * yield `undefined` (omit the tag) rather than a broken relative value.
 *
 * `path` may already be absolute (a media-API URL), in which case it is returned unchanged.
 */
export function absoluteSocialUrl(path: unknown, siteUrl: unknown): string | undefined {
  const candidate = pickMeta(path)
  if (!candidate) return undefined
  if (/^https?:\/\//i.test(candidate)) return candidate

  const base = pickMeta(siteUrl)
  if (!base || !/^https?:\/\//i.test(base)) return undefined

  return `${base.replace(/\/+$/, '')}/${candidate.replace(/^\/+/, '')}`
}
