import type { Envelope, MediaAsset, MediaUsage, Paginated } from '~/types/models'
import { ApiError } from '~/utils/api-error'
import { MEDIA_PER_PAGE, type MediaKind } from '~/utils/media-query'

/** What an upload produced. `deduplicated` means the bytes already existed and no new asset was made. */
export interface MediaUploadResult {
  readonly asset: MediaAsset
  readonly deduplicated: boolean
}

/**
 * The Media Library's transport (doc 07). Consumes the EXISTING admin media endpoints unchanged —
 * upload processing, R2 storage, SHA-256 deduplication, image variants and BlurHash are all the
 * API's, and nothing here reimplements or second-guesses any of it.
 *
 * ONE INSTANCE PER BROWSING SURFACE, deliberately not a shared store. The library page and an open
 * picker are two independent views of the same collection: the operator can be searching "portrait"
 * in the picker while the page behind it sits on page 3 of everything. Shared state would make one
 * surface's search silently move the other's grid. They re-read from the API instead, which is also
 * what keeps a picker upload visible on the page after it closes.
 *
 * `locale: false` ON EVERY CALL. Admin DTOs are validated with `forbidNonWhitelisted` and none of
 * them declares `locale`, so an unsolicited `?locale=` is a 422 rather than a harmless extra
 * parameter (see `useApi`). Media is locale-agnostic: an asset is bytes, and its per-locale alt
 * arrives in the response for every locale at once.
 */
export function useMediaLibrary() {
  const api = useApi()

  const items = ref<MediaAsset[]>([])
  const total = ref(0)
  const totalPages = ref(1)
  const pending = ref(false)
  /** `403` is not "no media" — a different answer gets a different surface (D11-2). */
  const forbidden = ref(false)
  const failed = ref(false)

  /**
   * Monotonic request token. Typing into the search box issues a request per debounced keystroke and
   * the responses are not guaranteed to return in order — a slow "por" landing after "portrait"
   * would leave the wrong result set under the current query. Only the newest request may write.
   */
  let loadSeq = 0

  async function load(query: { q?: string, kind?: MediaKind, page?: number } = {}): Promise<void> {
    const seq = ++loadSeq
    pending.value = true
    forbidden.value = false
    failed.value = false
    try {
      const res = await api<Paginated<MediaAsset>>('/admin/media', {
        locale: false,
        // Absent rather than empty: `q: ''` and `kind: undefined` must not become `?q=&kind=` — the
        // API would treat an empty search as a search, and the URL would stop matching the state.
        query: {
          page: query.page ?? 1,
          perPage: MEDIA_PER_PAGE,
          ...(query.q ? { q: query.q } : {}),
          ...(query.kind ? { kind: query.kind } : {})
        }
      })
      if (seq !== loadSeq) return
      items.value = [...res.data]
      total.value = res.meta.total
      totalPages.value = res.meta.totalPages
    } catch (error) {
      // A superseded request's failure is not the current query's failure.
      if (seq !== loadSeq) return
      // A failed load must not leave the previous result set on screen pretending to be current.
      items.value = []
      total.value = 0
      totalPages.value = 1
      if (error instanceof ApiError && error.status === 403) forbidden.value = true
      else failed.value = true
    } finally {
      if (seq === loadSeq) pending.value = false
    }
  }

  /**
   * Upload through the governed pipeline (`POST /admin/media`).
   *
   * `FormData`, with NO explicit `content-type`: the boundary is generated by the browser and a
   * hand-set `multipart/form-data` header would omit it, so the API would reject a body it cannot
   * split. Letting fetch set the header is the fix, not an oversight.
   *
   * DEDUPLICATION IS A NORMAL OUTCOME, NOT AN ERROR. Byte-identical bytes return the EXISTING asset
   * with `200 + meta.deduplicated`, where a new asset is `201` and carries no `meta` at all. Both
   * are successes and both yield a usable id, so the caller gets one shape and an honest flag rather
   * than having to know which status it got.
   */
  async function upload(file: File): Promise<MediaUploadResult> {
    const body = new FormData()
    body.append('file', file)
    const res = await api<Envelope<MediaAsset> & { meta?: { deduplicated?: boolean } }>('/admin/media', {
      method: 'POST',
      locale: false,
      body
    })
    return { asset: res.data, deduplicated: res.meta?.deduplicated === true }
  }

  /**
   * One asset by id.
   *
   * The picker needs this and cannot avoid it: a consumer stores only a `mediaAssetId`, and the
   * descriptor it would otherwise preview from is a different shape everywhere it appears — the
   * About portrait arrives as a `PublicMediaImageDescriptor` with no filename, an article cover
   * will arrive as its own. Resolving the id against the admin endpoint gives every consumer the
   * same full descriptor without any of them having to hand one down.
   */
  async function get(id: string): Promise<MediaAsset> {
    const res = await api<Envelope<MediaAsset>>(`/admin/media/${id}`, { locale: false })
    return res.data
  }

  /** Every record referencing an asset — what blocks a delete, and what the operator is shown. */
  async function usages(id: string): Promise<readonly MediaUsage[]> {
    const res = await api<Envelope<readonly MediaUsage[]>>(`/admin/media/${id}/usages`, { locale: false })
    return res.data
  }

  /**
   * Delete an asset. Resolves `{ deleted: true }`, or `{ deleted: false, usages }` when the API
   * refuses because the asset is referenced.
   *
   * THE 409 BODY IS NOT PARSED. It is documented as enumerating the usages but has no schema in the
   * contract, and the generated types therefore cannot describe it — reading it would mean
   * hand-shaping an untyped response, which is exactly what generating types from the contract
   * exists to prevent. `GET :id/usages` returns the same information under a typed schema, so the
   * refusal is confirmed by the status and the detail is fetched from the endpoint built for it.
   *
   * A failed usages lookup does NOT become a failed delete: the delete was still correctly refused,
   * and the caller renders the block without the list rather than reporting the wrong outcome.
   */
  async function remove(id: string): Promise<{ deleted: boolean, usages: readonly MediaUsage[] }> {
    try {
      // `unknown`, not `void`: the endpoint answers 204 with no body, and `void` as a type ARGUMENT
      // is rejected by `@typescript-eslint/no-invalid-void-type`. The value is discarded either way.
      await api<unknown>(`/admin/media/${id}`, { method: 'DELETE', locale: false })
      return { deleted: true, usages: [] }
    } catch (error) {
      if (error instanceof ApiError && error.status === 409) {
        const blocking = await usages(id).catch(() => [] as readonly MediaUsage[])
        return { deleted: false, usages: blocking }
      }
      throw error
    }
  }

  return { items, total, totalPages, pending, forbidden, failed, load, get, upload, usages, remove }
}
