import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Page } from '@playwright/test'
const control = `http://127.0.0.1:${Number(process.env.CI_OVERVIEW_MOCK_PORT ?? 4801)}`
async function signIn(page: Page) { await page.goto('/dashboard/login'); await page.locator('input[type=email]').fill('owner@example.com'); await page.locator('input[type=password]').fill('e2e-password-1234'); await page.locator('button[type=submit]').click(); await page.waitForURL('**/dashboard') }
test.beforeEach(async ({ page }) => { await page.request.post(`${control}/__e2e/reset`) })
test('renders supported totals, no fabricated optional totals, responsive layout and axe', async ({ page }) => {
  await signIn(page); await expect(page.locator('[data-overview-page]')).toBeVisible(); await expect(page.locator('[data-overview-total="articles"]')).toContainText('7'); await expect(page.locator('[data-overview-total="projects"]')).toContainText('3'); await expect(page.locator('[data-overview-attention-active]')).toContainText('2'); await expect(page.locator('[data-overview-total="messages"]')).toHaveCount(0); await expect(page.locator('[data-overview-page]')).not.toContainText(/\[object Object\]|__v_isRef|_value|\bdep\b/); await expect(page.locator('[data-overview-card="skills"] [data-overview-total]')).toHaveCount(0); await expect(page.locator('[data-overview-card="testimonials"] [data-overview-total]')).toHaveCount(0)
  const calls = await (await page.request.get(`${control}/__e2e/requests`)).json() as { calls: Array<{ path: string, query: string }> }; expect(calls.calls).toEqual(expect.arrayContaining([{ path: '/api/v1/admin/articles', query: '?page=1&perPage=1' }, { path: '/api/v1/admin/projects', query: '?page=1&perPage=1' }, { path: '/api/v1/admin/messages', query: '?isRead=false&isArchived=false&perPage=1' }])); expect(calls.calls).toHaveLength(3)
  await page.setViewportSize({ width: 380, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1); expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()).violations).toEqual([]); await page.locator('[data-overview-card="articles"] a').click(); await expect(page).toHaveURL(/\/dashboard\/articles$/); await page.goto('/dashboard'); await expect(page.locator('[data-overview-action="new-project"]')).toBeVisible(); await page.locator('[data-overview-action="new-project"]').click(); await expect(page).toHaveURL(/\/dashboard\/projects\/new$/)
})
test('one failed snapshot remains isolated and retries', async ({ page }) => { await page.request.post(`${control}/__e2e/state`, { data: { failing: 'articles' } }); await signIn(page); await expect(page.locator('[data-overview-unavailable="articles"]')).toBeVisible(); await expect(page.locator('[data-overview-total="projects"]')).toContainText('3'); await expect(page.locator('[data-overview-action="new-article"]')).toBeVisible(); await page.locator('[data-overview-action="new-article"]').click(); await expect(page).toHaveURL(/\/dashboard\/articles\/new$/); await page.goto('/dashboard'); await expect(page.locator('[data-overview-unavailable="articles"]')).toBeVisible(); await page.request.post(`${control}/__e2e/state`, { data: { failing: null } }); await page.locator('[data-overview-retry="articles"]').click(); await expect(page.locator('[data-overview-total="articles"]')).toContainText('7') })
test('Arabic shell stays RTL on the unprefixed Dashboard route', async ({ page }) => { await page.context().addCookies([{ name: 'dashboard_locale', value: 'ar', url: 'http://127.0.0.1:4800' }]); await signIn(page); await expect(page.locator('[data-shell="dashboard"]')).toHaveAttribute('dir', 'rtl'); await expect(page).toHaveURL(/\/dashboard$/); await expect(page.locator('[data-overview-page]')).toContainText(/[؀-ۿ]/) })
