<script setup lang="ts">
// Projects index (FR-PUB-030). Featured-first, filterable by technology, published-only — all three
// enforced by the API (D09-8); this page owns only the query and the presentation.
//
// Filter and page state live in the URL (D13-4): a filtered view is linkable, survives reload and
// back/forward, and is legible to crawlers. The canonical URL is always the unfiltered index (doc 22),
// so a filter never spawns a competing indexable page.
const { t } = useI18n()
const route = useRoute()
const router = useRouter()

// Query rules live in `~/utils/projects-query` as pure functions so each one is unit-tested; every
// one of them is invisible in the rendered output until it is wrong.
const page = computed(() => readPage(route.query))
const technology = computed(() => readTechnology(route.query))

const { data, status, error, refresh } = await useProjectsList({
  page: () => page.value,
  technology: () => technology.value
})
const { data: technologies } = await useProjectTechnologies()

// Split pending into initial-load (skeleton) vs a filter/page change with content already on screen
// (branded overlay) — useAsyncData keeps the previous `data` while refetching (doc 13 §9.1).
const hasData = computed(() => !!data.value)
const initialPending = computed(() => status.value === 'pending' && !hasData.value)
const refreshing = computed(() => status.value === 'pending' && hasData.value)
// A list page shows real empty copy; optional home sections omit themselves instead (doc 13 §9.1).
const isEmpty = computed(() => !!data.value && data.value.data.length === 0)
// "No projects at all" and "no matches for this filter" are different situations and read differently.
const isFilteredEmpty = computed(() => isEmpty.value && technology.value !== undefined)

/**
 * Writing the filter to the URL resets `page`: keeping page 3 while switching filters would land on an
 * out-of-range page and render an empty list that looks like a broken filter.
 *
 * `push`, NOT `replace` — a deliberate reversal of the earlier decision, which the control change
 * invalidates. `replace` was chosen so a SELECT could not stack one history entry per keystroke while
 * a visitor arrowed through options. A chip row has no intermediate states: every change is one
 * deliberate press, and `ProjectFilter` refuses to emit when the already-pressed chip is pressed
 * again, so an identical URL is never pushed. With `push`, Back undoes a filter — which is what
 * Back/Forward support has to mean for a control whose whole state lives in the URL.
 */
function onTechnologyChange(value: string | undefined): void {
  router.push({ path: route.path, query: buildFilterQuery(value) })
}

/** Pagination must carry the active filter, or paging silently widens the result set. */
function pageLink(target: number) {
  return { query: buildPageQuery(technology.value, target) }
}

// A visible trail on the index too: Home is otherwise only reachable through the header, and the
// BreadcrumbList below must mirror something the visitor can actually see (doc 22 §4).
const crumbs = computed(() => [{ label: t('nav.home'), to: '/' }, { label: t('nav.projects') }])

const siteConfig = useSiteConfig()
const localePath = useLocalePath()
useSchemaOrg(() => [
  defineBreadcrumb({
    itemListElement: crumbs.value.map(crumb => ({
      name: crumb.label,
      item: crumb.to ? `${siteConfig.url}${localePath(crumb.to)}` : undefined
    }))
  })
])

useSeoMeta({
  title: () => t('seo.projects.title'),
  description: () => t('seo.projects.description'),
  ogTitle: () => `${t('seo.projects.title')} — ${t('brand.name')}`,
  ogDescription: () => t('seo.projects.description')
})

// Canonical + hreflang are generated by @nuxtjs/i18n under strict SEO (D22-7), which excludes the query
// string — so `/projects?technology=…` canonicalizes to `/projects` exactly as doc 22 requires. A
// second canonical here would duplicate the tag and fight the global one; verified in the rendered
// output rather than assumed.
</script>

<template>
  <UContainer class="py-[var(--space-section)]">
    <UiBreadcrumbs :items="crumbs" :label="t('projects.breadcrumbLabel')" />

    <header class="mt-10 max-w-2xl">
      <p class="kicker text-dimmed">{{ t('nav.projects') }}</p>
      <h1 class="mt-4 font-display text-display text-highlighted text-balance">
        {{ t('projects.title') }}
      </h1>
      <p class="mt-5 text-body-lg text-muted text-pretty">{{ t('projects.description') }}</p>
    </header>

    <div class="mt-10">
      <ProjectFilter
        :technologies="technologies ?? []"
        :model-value="technology"
        :disabled="Boolean(error)"
        @update:model-value="onTechnologyChange"
      />
    </div>

    <!--
      The result count, localized.

      COUNT-AGNOSTIC PHRASING ON PURPOSE — "Case studies: 7", not "7 case studies". This app has no
      pluralized message anywhere, and vue-i18n's default plural rules do not cover Arabic's six
      categories, so a pluralized string here would drag a custom `pluralRules` registration in as a
      side effect of a listing change. The label form is already the house convention
      (`dashboard.unreadBadgeLabel`), and it is correct in both languages at every count.

      The digits stay Western in both locales — `{count}` interpolates the raw number, which is what
      D03-4 requires and what `formatDate`/`formatMonthYear` pin explicitly with `numberingSystem`.

      `aria-live="polite"` because filtering does not move focus: without it, a sighted visitor sees
      the number change and a screen-reader user gets nothing. It renders only alongside real data, so
      the region is not announced during the skeleton or the error state.
    -->
    <p
      v-if="data && data.data.length"
      class="mt-8 text-body-sm text-dimmed"
      aria-live="polite"
    >
      {{ t('projects.resultCount', { count: data.meta.total }) }}
    </p>

    <UiRequestState
      class="mt-10 block"
      :pending="initialPending"
      :refreshing="refreshing"
      :error="Boolean(error)"
      :empty="isEmpty"
      skeleton="work"
      :count="4"
      @retry="refresh()"
    >
      <template #error>
        <div class="rounded-card border border-default bg-elevated p-8" role="alert">
          <p class="font-display text-h3 text-highlighted">{{ t('projects.errorTitle') }}</p>
          <p class="mt-2 text-muted">{{ t('projects.errorBody') }}</p>
          <UButton class="mt-4" variant="subtle" color="neutral" @click="refresh()">
            {{ t('common.retry') }}
          </UButton>
        </div>
      </template>

      <template #empty>
        <div class="rounded-card border border-default bg-elevated p-8">
          <p class="font-display text-h3 text-highlighted">
            {{ isFilteredEmpty ? t('projects.emptyFilteredTitle') : t('projects.emptyTitle') }}
          </p>
          <p class="mt-2 text-muted">
            {{ isFilteredEmpty ? t('projects.emptyFilteredBody') : t('projects.emptyBody') }}
          </p>
          <!--
            A LINK, not a `@click` button. This action does exactly one thing — go to the unfiltered
            index — so a link is what it is, and a link WORKS BEFORE HYDRATION. A button's handler does
            not exist until Vue attaches it, so a visitor who lands on this server-rendered page and
            clicks immediately gets nothing. That race is real: it was caught as an intermittent e2e
            failure on the blog index, and this page had the identical defect. It also restores
            middle-click and open-in-new-tab, which a button silently removes.

            `query: {}` drops `technology` and `page` together — the same rule
            `buildFilterQuery(undefined)` encodes for the chips.
          -->
          <UButton
            v-if="isFilteredEmpty"
            class="mt-4"
            variant="subtle"
            color="neutral"
            :to="{ path: route.path, query: {} }"
          >
            {{ t('projects.filter.clear') }}
          </UButton>
        </div>
      </template>

      <!-- Order is the API's, rendered verbatim (D09-8) — no client-side sort. -->
      <!-- h2: these entries sit directly under the page h1, with no intervening section heading, so
           the default h3 would skip a level (WCAG heading order). -->
      <ContentWorkEntry
        v-for="project in (data?.data ?? [])"
        :key="project.id"
        :project="project"
        heading-level="h2"
      />
    </UiRequestState>

    <div v-if="data && data.data.length && data.meta.totalPages > 1" class="mt-12 flex justify-center">
      <UPagination
        :page="page"
        :total="data.meta.total"
        :items-per-page="data.meta.perPage"
        :to="pageLink"
      />
    </div>
  </UContainer>
</template>
