/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (no database access). */
        get: operations["HealthController_liveness_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — verifies the database connection. */
        get: operations["HealthController_readiness_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enabled content locales. */
        get: operations["LocalesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate; sets the refresh cookie and returns an access token. */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and issue a new access token. */
        post: operations["AuthController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh-token family and clear the cookie. */
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolved site settings for the requested locale. */
        get: operations["SettingsController_getSite_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full site settings with the per-locale translation map. */
        get: operations["SettingsAdminController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update site settings, incl. FR-DSH-052 head/tag fields. */
        patch: operations["SettingsAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories resolved to the requested locale. */
        get: operations["CategoriesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories with full translation maps. */
        get: operations["CategoriesAdminController_list_v1"];
        put?: never;
        /** Create a category with its translations. */
        post: operations["CategoriesAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category (409 if articles still reference it). */
        delete: operations["CategoriesAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Upsert category translations. */
        patch: operations["CategoriesAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags resolved to the requested locale. */
        get: operations["TagsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags with full translation maps. */
        get: operations["TagsAdminController_list_v1"];
        put?: never;
        /** Create a tag with its translations. */
        post: operations["TagsAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a tag. */
        delete: operations["TagsAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Upsert tag translations. */
        patch: operations["TagsAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published articles, resolved and filtered by locale. */
        get: operations["ArticlesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published article by its per-locale slug (drafts 404). */
        get: operations["ArticlesController_getBySlug_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List articles (any status) with full translation maps. */
        get: operations["ArticlesAdminController_list_v1"];
        put?: never;
        /** Create an article with translations, tags, and scheduling. */
        post: operations["ArticlesAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one article with its full translation map. */
        get: operations["ArticlesAdminController_get_v1"];
        put?: never;
        post?: never;
        /** Delete an article. */
        delete: operations["ArticlesAdminController_remove_v1"];
        options?: never;
        head?: never;
        /** Update an article; upserts translations and status transitions. */
        patch: operations["ArticlesAdminController_update_v1"];
        trace?: never;
    };
    "/api/v1/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The read-only code-defined permission catalog (D10-9). */
        get: operations["RolesAdminController_getPermissions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles with their granted permission keys. */
        get: operations["RolesAdminController_listRoles_v1"];
        put?: never;
        /** Create a custom role and grant it permission keys. */
        post: operations["RolesAdminController_createRole_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one role. */
        get: operations["RolesAdminController_getRole_v1"];
        put?: never;
        post?: never;
        /** Delete a custom role (system role or still-assigned role → 422). */
        delete: operations["RolesAdminController_deleteRole_v1"];
        options?: never;
        head?: never;
        /** Update a custom role (system roles reject edits with 422). */
        patch: operations["RolesAdminController_updateRole_v1"];
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List operator accounts with their role and active status. */
        get: operations["UsersAdminController_list_v1"];
        put?: never;
        /** Create an operator account with a role. */
        post: operations["UsersAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign a role or activate/deactivate an account. */
        patch: operations["UsersAdminController_update_v1"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LivenessStatus: {
            /** @example ok */
            status: string;
            /**
             * @description Process uptime in seconds.
             * @example 12345.6
             */
            uptime: number;
            /** @example 2026-07-13T12:00:00.000Z */
            timestamp: string;
        };
        FieldErrorDto: {
            /**
             * @description Dotted path to the offending field.
             * @example translations[0].slug
             */
            field: string;
            /** @example Slug already exists for locale 'en'. */
            message: string;
        };
        ProblemDetailsDto: {
            /**
             * @description A URI reference identifying the problem type.
             * @example /problems/validation
             */
            type: string;
            /** @example Validation failed */
            title: string;
            /** @example 422 */
            status: number;
            /** @example 2 fields failed validation. */
            detail: string;
            /** @example /api/v1/admin/articles */
            instance: string;
            /** @description Present on 422 responses only. */
            errors?: components["schemas"]["FieldErrorDto"][];
        };
        ReadinessStatus: {
            /** @example ok */
            status: string;
            /**
             * @example up
             * @enum {string}
             */
            database: "up";
        };
        LocaleEntity: {
            /**
             * @description Two-letter locale code (primary key).
             * @example en
             */
            code: string;
            /** @example English */
            name: string;
            /**
             * @description Endonym shown in the locale switcher.
             * @example العربية
             */
            nativeName: string;
            /**
             * @description Text direction as data (D09-5).
             * @example ltr
             * @enum {string}
             */
            dir: "ltr" | "rtl";
        };
        AuthUserRoleEntity: {
            /**
             * Format: uuid
             * @example 018f9d3c-1a2b-7c3d-8e4f-5a6b7c8d9e0f
             */
            id: string;
            /** @example OWNER */
            name: string;
        };
        AuthUserEntity: {
            /**
             * Format: uuid
             * @example 018f9d3c-1a2b-7c3d-8e4f-5a6b7c8d9e0f
             */
            id: string;
            /**
             * Format: email
             * @example owner@example.com
             */
            email: string;
            role: components["schemas"]["AuthUserRoleEntity"];
        };
        LoginResponse: {
            /**
             * @description 15-minute access token; the refresh token is set as an httpOnly cookie.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            user: components["schemas"]["AuthUserEntity"];
        };
        LoginDto: {
            /**
             * Format: email
             * @example owner@example.com
             */
            email: string;
            /** @example change-me-minimum-12-chars */
            password: string;
        };
        RefreshResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
        };
        LogoutResponse: {
            /** @example true */
            success: boolean;
        };
        ProfileLinkEntity: {
            /** @example GitHub */
            label: string;
            /**
             * Format: uri
             * @example https://github.com/eslammuatamed
             */
            url: string;
            /**
             * @description Icon token (UI hint).
             * @example i-simple-icons-github
             */
            icon?: string;
        };
        CustomMetaEntity: {
            /** @example theme-color */
            name: string;
            /** @example #0b0b0f */
            content: string;
        };
        PublicSiteSettingsEntity: {
            /** @example Eslam Muatamed */
            siteName: string | null;
            /** @example Software engineer & architect */
            tagline: string | null;
            /** @example Eslam Muatamed */
            defaultMetaTitle: string | null;
            /** @example Portfolio, case studies, and writing. */
            defaultMetaDescription: string | null;
            profileLinks: components["schemas"]["ProfileLinkEntity"][];
            /** @example Open to select consulting engagements */
            availabilityStatus: string | null;
            /**
             * @description Google Search Console token.
             * @example google-abc123
             */
            googleSiteVerification: string | null;
            /**
             * @description Bing Webmaster token.
             * @example bing-def456
             */
            bingSiteVerification: string | null;
            /** @description Present only when analytics is enabled; null otherwise (FR-DSH-052, D20-5). */
            analytics?: {
                /**
                 * @example ga4
                 * @enum {string}
                 */
                provider: "ga4" | "gtm";
                /** @example G-XXXXXXXXXX */
                measurementId: string;
            } | null;
            customMetas: components["schemas"]["CustomMetaEntity"][];
            /**
             * @description Locales with a translation.
             * @example [
             *       "en",
             *       "ar"
             *     ]
             */
            availableLocales: string[];
        };
        SiteSettingsTranslationEntity: {
            /** @example Eslam Muatamed */
            siteName: string | null;
            /** @example Software engineer & architect */
            tagline: string | null;
            defaultMetaTitle: string | null;
            defaultMetaDescription: string | null;
        };
        AdminSiteSettingsEntity: {
            /** Format: uuid */
            id: string;
            profileLinks: components["schemas"]["ProfileLinkEntity"][];
            availabilityStatus: string | null;
            /** Format: uuid */
            resumeAssetId: string | null;
            googleSiteVerification: string | null;
            bingSiteVerification: string | null;
            /** @enum {string|null} */
            analyticsProvider: "ga4" | "gtm" | null;
            analyticsMeasurementId: string | null;
            /** @example false */
            analyticsEnabled: boolean;
            customMetas: components["schemas"]["CustomMetaEntity"][];
            /** @description Translation map keyed by locale code, e.g. { "en": {…}, "ar": {…} }. */
            translations: {
                [key: string]: components["schemas"]["SiteSettingsTranslationEntity"];
            };
        };
        ProfileLinkDto: {
            /** @example GitHub */
            label?: string;
            /** @example https://github.com/eslammuatamed */
            url?: string;
            /** @example i-simple-icons-github */
            icon?: string;
        };
        CustomMetaDto: {
            /** @example theme-color */
            name?: string;
            /** @example #0b0b0f */
            content?: string;
        };
        SettingsTranslationDto: {
            /**
             * @description Two-letter locale; must be enabled.
             * @example ar
             */
            locale?: string;
            /** @example Eslam Muatamed */
            siteName?: string;
            /** @example Software engineer & architect */
            tagline?: string;
            /** @example Eslam Muatamed */
            defaultMetaTitle?: string;
            /** @example Portfolio, case studies, and writing. */
            defaultMetaDescription?: string;
        };
        UpdateSettingsDto: {
            profileLinks?: components["schemas"]["ProfileLinkDto"][];
            /** @example Open to select consulting engagements */
            availabilityStatus?: string;
            /** @example google-abc123 */
            googleSiteVerification?: string;
            /** @example bing-def456 */
            bingSiteVerification?: string;
            /** @enum {string} */
            analyticsProvider?: "ga4" | "gtm";
            /** @example G-XXXXXXXXXX */
            analyticsMeasurementId?: string;
            /**
             * @description Analytics is off by default (D20-5).
             * @example false
             */
            analyticsEnabled?: boolean;
            customMetas?: components["schemas"]["CustomMetaDto"][];
            /** @description Per-locale upserts. */
            translations?: components["schemas"]["SettingsTranslationDto"][];
        };
        PublicCategoryEntity: {
            /** Format: uuid */
            id: string;
            /** @example Engineering */
            name: string;
            /**
             * @description Per-locale slug (D04-2).
             * @example engineering
             */
            slug: string;
            /** @example Systems, architecture, and craft. */
            description: string | null;
            /**
             * @example [
             *       "en",
             *       "ar"
             *     ]
             */
            availableLocales: string[];
        };
        CategoryTranslationEntity: {
            /** @example Engineering */
            name: string;
            /** @example engineering */
            slug: string;
            description: string | null;
        };
        AdminCategoryEntity: {
            /** Format: uuid */
            id: string;
            /** @description Translation map keyed by locale code. */
            translations: {
                [key: string]: components["schemas"]["CategoryTranslationEntity"];
            };
        };
        CategoryTranslationDto: {
            /**
             * @description Two-letter locale; must be enabled.
             * @example en
             */
            locale: string;
            /** @example Engineering */
            name: string;
            /** @example engineering */
            slug: string;
            /** @example Systems, architecture, and craft. */
            description?: string;
        };
        CreateCategoryDto: {
            /** @description At least one locale translation. */
            translations: components["schemas"]["CategoryTranslationDto"][];
        };
        UpdateCategoryDto: {
            translations?: components["schemas"]["CategoryTranslationDto"][];
        };
        PublicTagEntity: {
            /** Format: uuid */
            id: string;
            /** @example NestJS */
            name: string;
            /**
             * @description Per-locale slug (D04-2).
             * @example nestjs
             */
            slug: string;
            /**
             * @example [
             *       "en",
             *       "ar"
             *     ]
             */
            availableLocales: string[];
        };
        TagTranslationEntity: {
            /** @example NestJS */
            name: string;
            /** @example nestjs */
            slug: string;
        };
        AdminTagEntity: {
            /** Format: uuid */
            id: string;
            /** @description Translation map keyed by locale code. */
            translations: {
                [key: string]: components["schemas"]["TagTranslationEntity"];
            };
        };
        TagTranslationDto: {
            /**
             * @description Two-letter locale; must be enabled.
             * @example en
             */
            locale: string;
            /** @example NestJS */
            name: string;
            /** @example nestjs */
            slug: string;
        };
        CreateTagDto: {
            /** @description At least one locale translation. */
            translations: components["schemas"]["TagTranslationDto"][];
        };
        UpdateTagDto: {
            translations?: components["schemas"]["TagTranslationDto"][];
        };
        ArticleTaxonomyRefEntity: {
            /** Format: uuid */
            id: string;
            /** @example Engineering */
            name: string;
            /** @example engineering */
            slug: string;
        };
        PublicArticleListItemEntity: {
            /** Format: uuid */
            id: string;
            /** @example Designing a modular monolith */
            title: string;
            /** @example designing-a-modular-monolith */
            slug: string;
            /** @example Why one deployable with hard module seams beats microservices here. */
            excerpt: string;
            /**
             * @description Computed reading time in minutes.
             * @example 7
             */
            readingTimeMin: number;
            /** Format: date-time */
            publishAt: string | null;
            /**
             * Format: uuid
             * @description Cover MediaAsset id.
             */
            coverImageId: string | null;
            category: components["schemas"]["ArticleTaxonomyRefEntity"];
            tags: components["schemas"]["ArticleTaxonomyRefEntity"][];
            /**
             * @example [
             *       "en",
             *       "ar"
             *     ]
             */
            availableLocales: string[];
        };
        PageMeta: {
            /**
             * @description Current page (1-based).
             * @example 1
             */
            page: number;
            /**
             * @description Items per page (max 50).
             * @example 12
             */
            perPage: number;
            /**
             * @description Total matching items.
             * @example 42
             */
            total: number;
            /**
             * @description Total pages for the current perPage.
             * @example 4
             */
            totalPages: number;
        };
        PublicArticleDetailEntity: {
            /** Format: uuid */
            id: string;
            /** @example Designing a modular monolith */
            title: string;
            /** @example designing-a-modular-monolith */
            slug: string;
            /** @example Why one deployable with hard module seams beats microservices here. */
            excerpt: string;
            /**
             * @description Computed reading time in minutes.
             * @example 7
             */
            readingTimeMin: number;
            /** Format: date-time */
            publishAt: string | null;
            /**
             * Format: uuid
             * @description Cover MediaAsset id.
             */
            coverImageId: string | null;
            category: components["schemas"]["ArticleTaxonomyRefEntity"];
            tags: components["schemas"]["ArticleTaxonomyRefEntity"][];
            /**
             * @example [
             *       "en",
             *       "ar"
             *     ]
             */
            availableLocales: string[];
            /**
             * @description Locale code → that locale’s slug, for locale switching.
             * @example {
             *       "en": "building-x",
             *       "ar": "binaa-x"
             *     }
             */
            slugs: {
                [key: string]: string;
            };
            /**
             * @description Opaque Markdown (D01-5).
             * @example # Heading
             *
             *     Opaque Markdown body…
             */
            body: string;
            metaTitle: string | null;
            metaDescription: string | null;
            /** Format: uuid */
            ogImageId: string | null;
            /** Format: uri */
            canonicalUrl: string | null;
        };
        AdminArticleTranslationEntity: {
            title: string;
            slug: string;
            excerpt: string;
            /** @description Opaque Markdown (D01-5). */
            body: string;
            /** @example 7 */
            readingTimeMin: number;
            metaTitle: string | null;
            metaDescription: string | null;
            /** Format: uuid */
            ogImageId: string | null;
            /** Format: uri */
            canonicalUrl: string | null;
        };
        AdminArticleEntity: {
            /** Format: uuid */
            id: string;
            /**
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
            /** Format: date-time */
            publishAt: string | null;
            /** Format: uuid */
            categoryId: string;
            /** Format: uuid */
            coverImageId: string | null;
            /** @description Associated tag ids. */
            tagIds: string[];
            /** @description Translation map keyed by locale code. */
            translations: {
                [key: string]: components["schemas"]["AdminArticleTranslationEntity"];
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ArticleTranslationDto: {
            /**
             * @description Two-letter locale; must be enabled.
             * @example en
             */
            locale: string;
            /** @example Designing a modular monolith */
            title: string;
            /** @example designing-a-modular-monolith */
            slug: string;
            /** @example Why one deployable with hard module seams beats microservices here. */
            excerpt: string;
            /**
             * @description Opaque Markdown (D01-5).
             * @example # Heading
             *
             *     Opaque Markdown…
             */
            body: string;
            metaTitle?: string;
            metaDescription?: string;
            /** Format: uuid */
            ogImageId?: string;
            /** Format: uri */
            canonicalUrl?: string;
        };
        CreateArticleDto: {
            /**
             * Format: uuid
             * @description Required category (FR-CNT-050).
             */
            categoryId: string;
            /**
             * @default DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
            /**
             * Format: date-time
             * @description Required and future when SCHEDULED.
             */
            publishAt?: string;
            /**
             * Format: uuid
             * @description Cover MediaAsset id.
             */
            coverImageId?: string;
            /** @description Tag ids (optional). */
            tagIds?: string[];
            /** @description At least one locale translation. */
            translations: components["schemas"]["ArticleTranslationDto"][];
        };
        UpdateArticleDto: {
            /** Format: uuid */
            categoryId?: string;
            /** @enum {string} */
            status?: "DRAFT" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
            /** Format: date-time */
            publishAt?: string;
            /** Format: uuid */
            coverImageId?: string;
            tagIds?: string[];
            translations?: components["schemas"]["ArticleTranslationDto"][];
        };
        PermissionCatalogEntity: {
            /**
             * @description Every grantable permission key. The reserved "*" wildcard grants all of them.
             * @example [
             *       "articles.read",
             *       "articles.publish",
             *       "settings.update"
             *     ]
             */
            permissions: string[];
        };
        RoleEntity: {
            /** Format: uuid */
            id: string;
            /** @example Editor */
            name: string;
            /** @example Can manage content but not settings or users. */
            description: string | null;
            /**
             * @description System roles (OWNER) cannot be edited or deleted.
             * @example false
             */
            isSystem: boolean;
            /**
             * @description Granted permission keys (or "*").
             * @example [
             *       "articles.read",
             *       "articles.create",
             *       "articles.publish"
             *     ]
             */
            permissions: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateRoleDto: {
            /** @example Editor */
            name: string;
            /** @example Manages content; no settings or user access. */
            description?: string;
            /**
             * @description Catalog keys or "*".
             * @example [
             *       "articles.read",
             *       "articles.create",
             *       "articles.publish"
             *     ]
             */
            permissions: string[];
        };
        UpdateRoleDto: {
            /** @example Senior Editor */
            name?: string;
            description?: string;
            /**
             * @example [
             *       "articles.read",
             *       "articles.update"
             *     ]
             */
            permissions?: string[];
        };
        UserRoleRefEntity: {
            /** Format: uuid */
            id: string;
            /** @example Editor */
            name: string;
        };
        UserEntity: {
            /** Format: uuid */
            id: string;
            /**
             * Format: email
             * @example editor@example.com
             */
            email: string;
            /** @example true */
            isActive: boolean;
            role: components["schemas"]["UserRoleRefEntity"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateUserDto: {
            /**
             * Format: email
             * @example editor@example.com
             */
            email: string;
            /** @example change-me-minimum-12-chars */
            password: string;
            /**
             * Format: uuid
             * @description Assigned role id.
             */
            roleId: string;
            /** @default true */
            isActive: boolean;
        };
        UpdateUserDto: {
            /** Format: uuid */
            roleId?: string;
            /** @description Deactivating blocks login and denies all grants at once. */
            isActive?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_liveness_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LivenessStatus"];
                    };
                };
            };
        };
    };
    HealthController_readiness_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReadinessStatus"];
                    };
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    LocalesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled locales, ordered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LocaleEntity"];
                    };
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LoginResponse"];
                    };
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Malformed login payload. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Login rate limit exceeded (5 / 15 min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_refresh_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RefreshResponse"];
                    };
                };
            };
            /** @description Missing, invalid, expired, or revoked refresh token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Refresh rate limit exceeded (30 / hour). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LogoutResponse"];
                    };
                };
            };
        };
    };
    SettingsController_getSite_v1: {
        parameters: {
            query?: {
                /** @description Two-letter locale code, validated against enabled locales. */
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public settings resolved to ?locale=. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicSiteSettingsEntity"];
                    };
                };
            };
            /** @description Unknown or disabled locale. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Malformed query parameters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    SettingsAdminController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminSiteSettingsEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    SettingsAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsDto"];
            };
        };
        responses: {
            /** @description The updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminSiteSettingsEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    CategoriesController_list_v1: {
        parameters: {
            query?: {
                /** @description Two-letter locale code, validated against enabled locales. */
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories in the requested locale. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicCategoryEntity"];
                    };
                };
            };
            /** @description Unknown or disabled locale. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Malformed query parameters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    CategoriesAdminController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminCategoryEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    CategoriesAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminCategoryEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Validation error or slug already in use. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    CategoriesAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Category not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Category is still referenced by articles. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    CategoriesAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminCategoryEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Category not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Validation error or slug already in use. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TagsController_list_v1: {
        parameters: {
            query?: {
                /** @description Two-letter locale code, validated against enabled locales. */
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags in the requested locale. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicTagEntity"];
                    };
                };
            };
            /** @description Unknown or disabled locale. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Malformed query parameters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TagsAdminController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminTagEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TagsAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminTagEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Validation error or slug already in use. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TagsAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Tag not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TagsAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminTagEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Tag not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Validation error or slug already in use. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticlesController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                locale?: string;
                /** @description Category slug (in ?locale=). */
                category?: string;
                /** @description Tag slug (in ?locale=). */
                tag?: string;
                /** @description Free-text match on title/excerpt. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated published articles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicArticleListItemEntity"][];
                        meta: components["schemas"]["PageMeta"];
                    };
                };
            };
            /** @description Unknown or disabled locale. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Malformed query parameters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticlesController_getBySlug_v1: {
        parameters: {
            query?: {
                /** @description Two-letter locale code, validated against enabled locales. */
                locale?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicArticleDetailEntity"];
                    };
                };
            };
            /** @description Unknown or disabled locale. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description No published article with this slug in the locale. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Malformed query parameters. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticlesAdminController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                status?: "DRAFT" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminArticleEntity"][];
                        meta: components["schemas"]["PageMeta"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticlesAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArticleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminArticleEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Validation error, slug collision, or invalid publishAt. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticlesAdminController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminArticleEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticlesAdminController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticlesAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArticleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminArticleEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Validation error, slug collision, or invalid publishAt. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    RolesAdminController_getPermissions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PermissionCatalogEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    RolesAdminController_listRoles_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    RolesAdminController_createRole_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Unknown permission key or duplicate name. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    RolesAdminController_getRole_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Role not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    RolesAdminController_deleteRole_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Role not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description System role or still assigned to users. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    RolesAdminController_updateRole_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RoleEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Role not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description System role, unknown key, or duplicate name. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UsersAdminController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UsersAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Unknown role or duplicate email. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UsersAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserEntity"];
                    };
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Missing the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Unknown role. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Admin rate limit exceeded (300 / min). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
}
